// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import InvoicePdfDownloadController from "controllers/invoice_pdf_download_controller"
import LoginStatusController from "controllers/login_status_controller"
import MenuController from "controllers/menu_controller"
application.register("invoice-pdf-download", InvoicePdfDownloadController)
application.register("login-status", LoginStatusController)
application.register("menu", MenuController)
